
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import { ThemeToggle } from "@/components/theme-toggle"
import { ThemeProvider } from "@/components/theme-provider";
import "../globals.css";
import { MainNav } from "@/components/main-nav";
import { BreadcrumbWithCustomSeparator } from '@/components/breadcrumb'
import { useParams } from "next/navigation";

import { useRouter } from "next/router";
import MainFooter from "@/components/footer";
import { SelectDemo } from "@/components/select";



const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    const breadcrumbsData = [
        { href: "/", label: "Home" },
        { href: "/men", label: "Men" }
      ];
    
  return (
      <html lang="en" suppressHydrationWarning>
     
      <body  className={cn(
          "min-h-screen bg-background font-mono antialiased mx-[2rem] ",
          fontSans.variable
        )}>

           <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
            >
              <MainNav  className=" mt-5"/>
              
              <BreadcrumbWithCustomSeparator items={breadcrumbsData} />
              <div className='filter flex justify-between w-full px-5 mt-5  overflow-hidden relative bg-green-500'>
            <div className=" self-center font-bold">FILTERS</div>
            <div className=" px-5 py-5 flex w-[19rem] justify-between "><h1 className=" self-center font-bold">
            SORT BY :
            </h1>
             <SelectDemo/>
             </div>

             </div>
             <div className=" flex justify-between">
                <div className=" bg-yellow-500 flex-none w-1/5">
                        FILTERS CATEGORY
                </div>  

             <div className=" flex-grow">
             {children}
             </div>
             </div>
              <MainFooter/>
            </ThemeProvider>
            
         
            </body>
            
            
    </html>
  );
}
