
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import { ThemeToggle } from "@/components/theme-toggle"
import { ThemeProvider } from "@/components/theme-provider";
import "../globals.css";
import { MainNav } from "@/components/main-nav";

import { useRouter } from "next/router";
import MainFooter from "@/components/footer";
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning>
     
      <body  className={cn(
          "min-h-screen bg-background font-mono antialiased ",
          fontSans.variable
        )}>

           <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
            >
              <MainNav  className=" mt-5"/>
              
              {children}
              <MainFooter/>
            </ThemeProvider>
            
         
            </body>
            
            
    </html>
  );
}
